version: '3.3'
services:
  kaldi:
    image: "mymodel"
  web:
    build: ./web/server
    volumes:
      - ./web/server:/server
    ports:
      - "8080:8080"
  frontend:
    build: ./web/frontend
    volumes:
      - ./web/frontend:/usr/src/app
    ports:
      - "3000:3000"
