version: '3.3'
services:
  kaldi:
    image : bdockbockd/asr_kaldi
    volumes:
      - "./model/model:/model"
  web:
    image: bdockbockd/asr_web
    volumes:
      - ./web/server:/server
    ports:
      - "8080:8080"
  frontend:
    image : bdockbockd/asr_frontend
    volumes:
      - ./web/frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
