name: Docker Image CI

on:
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        git clone https://github.com/beesk135/asr_model.git
        docker-compose up
